In [1]:
import numpy as np

In [56]:
'''
Сгенерировать случайным образом матрицу размерностью 8х8 и вывести ее на экран (числа лежат в диапазоне от -10 до 10)
'''

arr = np.random.randint(-10, 10, (8, 8))

arr

array([[ -3,   8,   5,   8,  -9,   4,   5,  -2],
       [  2,  -4,  -6,  -1,  -3,   4,  -5,  -4],
       [  1,  -5,   3,   9,  -6,   4,   2,  -8],
       [ -9,  -5,   0,  -6,  -6, -10,  -4,  -2],
       [ -5,   3,   3,  -7, -10,   8,  -3,   6],
       [ -1,   0,   9,  -9,   0,   4,  -5,  -4],
       [ -6,  -1,  -9,  -4,  -2,   0,  -7,   2],
       [ -2,  -9,   5,   4,   9,  -9,  -9,   8]])

In [57]:
'''
Вывести центральную часть матрицы размерностью 4х4.
'''
arr[2:6, 2:6]

array([[  3,   9,  -6,   4],
       [  0,  -6,  -6, -10],
       [  3,  -7, -10,   8],
       [  9,  -9,   0,   4]])

In [58]:
'''
Удалить из исходной матрицы все строки, содержащие минимальный элемент.
'''
m = arr.min()
print(m)

-10


In [59]:
arr = np.delete(arr, [j for j, line in enumerate(arr) if m in line], 0)
arr

array([[-3,  8,  5,  8, -9,  4,  5, -2],
       [ 2, -4, -6, -1, -3,  4, -5, -4],
       [ 1, -5,  3,  9, -6,  4,  2, -8],
       [-1,  0,  9, -9,  0,  4, -5, -4],
       [-6, -1, -9, -4, -2,  0, -7,  2],
       [-2, -9,  5,  4,  9, -9, -9,  8]])

In [60]:
'''
Вставить в матрицу строку из минимального элемента перед первой строкой.
'''
arr_min = np.full(arr.shape[-1], m)
arr = np.insert(arr, 0, arr_min, 0)
arr

array([[-10, -10, -10, -10, -10, -10, -10, -10],
       [ -3,   8,   5,   8,  -9,   4,   5,  -2],
       [  2,  -4,  -6,  -1,  -3,   4,  -5,  -4],
       [  1,  -5,   3,   9,  -6,   4,   2,  -8],
       [ -1,   0,   9,  -9,   0,   4,  -5,  -4],
       [ -6,  -1,  -9,  -4,  -2,   0,  -7,   2],
       [ -2,  -9,   5,   4,   9,  -9,  -9,   8]])

In [61]:
'''
Вычислить сумму и среднее арифметическое всех элементов матрицы.
'''
print('Сумма элементов массива:', arr.sum())
print('Среднее арифметическое элементов массива:', arr.mean())

Сумма элементов массива: -117
Среднее арифметическое элементов массива: -2.0892857142857144
