In [2]:
import numpy as np

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2 = np.arange(2, 10, 2)
arr2

array([2, 4, 6, 8])

In [8]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr4 = np.arange(10.6, -10.8, -0.5)
arr4

array([ 10.6,  10.1,   9.6,   9.1,   8.6,   8.1,   7.6,   7.1,   6.6,
         6.1,   5.6,   5.1,   4.6,   4.1,   3.6,   3.1,   2.6,   2.1,
         1.6,   1.1,   0.6,   0.1,  -0.4,  -0.9,  -1.4,  -1.9,  -2.4,
        -2.9,  -3.4,  -3.9,  -4.4,  -4.9,  -5.4,  -5.9,  -6.4,  -6.9,
        -7.4,  -7.9,  -8.4,  -8.9,  -9.4,  -9.9, -10.4])

In [12]:
arr4.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [16]:
arr4.ndim

1

In [17]:
arr4.shape

(43,)

In [18]:
arr4.size

43

In [22]:
print(arr4.itemsize)
print(arr4.nbytes)

8
344


In [25]:
# Array nd 0
arr_0d = np.array(42)
arr_0d

array(42)

In [24]:
print(arr_0d.ndim)
print(arr_0d.shape)
print(arr_0d.size)

0
()
1


In [29]:
# Array nd 1
arr_1d = np.arange(1, 4, 1)
arr_1d

array([1, 2, 3])

In [30]:
print(arr_1d.ndim)
print(arr_1d.shape)
print(arr_1d.size)

1
(3,)
3


In [35]:
# Array nd 2
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)

2
(2, 3)
6


In [38]:
column = np.array([[1],
                   [2],
                   [3]])
column

array([[1],
       [2],
       [3]])

In [39]:
column.shape

(3, 1)

In [40]:
arr_3d = np.arange(12).reshape(2, 2, 3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [41]:
print(arr_3d.ndim)
print(arr_3d.shape)
print(arr_3d.size)

3
(2, 2, 3)
12


In [45]:
np.zeros(10).reshape(2, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [51]:
np.full((3, 4), 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [52]:
np.empty((2,3))

array([[3.52762871e-320, 0.00000000e+000, 6.91056428e-310],
       [6.91056463e-310, 6.91056441e-310, 6.91056428e-310]])

In [53]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [56]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [58]:
np.full_like(a, 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [59]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.linspace(0, 0.9, 10)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])